baseURL: 'https://verchk.alterdojec.me/'

theme: hugo-book

languageCode: 'ru-ru'
defaultContentLanguage: ru
languages:
  ru:
    title: 'Документация VerChk'
    languageName: Русский
    weight: 1
    contentDir: content/ru
  en:
    title: 'VerChk Docs'
    languageName: English
    weight: 2
    contentDir: content/en
  zh:
    title: 'VerChk 文档'
    languageName: 中文
    weight: 2
    contentDir: content/zh

params:
  BookTheme: dark
  BookRepo: "https://github.com/vobbla16/verchk-docs"
  BookSearch: true
  BookComments: false

menu:
  after:
    - name: GitHub repo
      params:
        rel: external
      url: https://github.com/vobbla16/verchk
      weight: 30
